name: Test & Lint
on: [push]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir-version: ['1.9', '1.10', '1.11']
        otp-version: ['22', '23']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
      - run: mix deps.get
        name: Fetch Dependencies
      - run: mix credo --strict
        name: Lint
      - run: mix format --check-formatted
        name: Check Formatting
      - run: mix test --no-start
        name: Run Tests
